### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by BoredTape** [jiuker/mysqlbinlog_network#1]
I create a demo to test this crate, all my code is copy from crates.io example.Then I got error when I run it.

platform:macOS Monterey 12.2.1
rust:rustc 1.63.0 (4b91a6ea7 2022-08-08)
cargo:cargo 1.63.0 (fd9c4297c 2022-07-01)
crate:mysqlbinlog-network = {git="https://github.com/jiuker/mysqlbinlog_network"} and mysqlbinlog-network = "1.0.9"

error:
![WechatIMG34028](https://user-images.githubusercontent.com/22056055/184569726-3df43ada-25af-4042-9bed-d1a527a4edb2.jpeg)

**Comment by jiuker** [comment]
I prefer you to use [mysql_common](https://crates.io/crates/mysql_common)
This branch will no longer be maintained

**Comment by BoredTape** [comment]
好的，那我去用mysql_common了
